### ISSUE TITLE
Emotion cards 

### ISSUE THREAD

**Issue by Vsxx** [ayserjamshidi/DarkBetrayal#29]
When you click on an emotion card for example <[Emotion Card] Sing "Good Day"> instead of learning this cards emote i relearned all the emotes that are already given to us from the start. tried it again with an emote i already had. even tho i had the emote i was still able to use the card and it also made me relearn all the emotes again. 
![image](https://user-images.githubusercontent.com/35045436/34501278-28ff7b10-efdc-11e7-8f88-6c15b8a87e8f.png)

**Comment by AyserJamshidi** [comment]
Build 210 includes a fix that is confirmed working and allows proper emotion learning.
