### ISSUE TITLE
Idian Depths Shugos <Battlefield Equipment Vendor>

### ISSUE THREAD

**Issue by Vsxx** [ayserjamshidi/DarkBetrayal#33]
The shugo's that have the tag <Battlefield Equipment Vendor> in the Idian depths are npcs that spawn 1 at a time, (currently they are all spawned)  they are supposed to be used to sell Blood Mark gear (discordant) for AP. they currently only let you sell normal items to them for kinah (npc name is Kikorinerk)

**Comment by AyserJamshidi** [comment]
Build 384 includes a fix that's tested and confirmed working.
