### ISSUE TITLE
Arena Ticket Quest

### ISSUE THREAD

**Issue by Actionshd** [ayserjamshidi/DarkBetrayal#42]
Accepting Arena Ticket Quest from Crucible Coliseum and completing it makes you acquire a bunch of other quests.
![aion0001](https://user-images.githubusercontent.com/35017185/34701139-24e8e26c-f4ac-11e7-8fc3-922b308e5fe6.jpg)

**Comment by AyserJamshidi** [comment]
Those quests activate upon hitting level 65.  I will change their activators later.

Duplicate of #13
