### ISSUE TITLE
Fearing through walls will cause you to fall through geodata.

### ISSUE THREAD

**Issue by Actionshd** [ayserjamshidi/DarkBetrayal#45]
**EDIT** Not just this corner but any part of the coliseum you will fall through it.
**EDIT AGAIN** Not just the coliseum but most walls will either throw you off the map or teleport you through it when feared.
![aion0003](https://user-images.githubusercontent.com/35017185/34733093-c4121d92-f52c-11e7-9e7b-f621243cfc45.jpg)
![aion0004](https://user-images.githubusercontent.com/35017185/34733095-c55d741c-f52c-11e7-8c59-4bc6fc00ab5e.jpg)

**Comment by AyserJamshidi** [comment]
Geodata is off right now.
